config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :contractors

  get 'welcome/index'

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:client_id, :firstname, :lastname, :address1, :address2, :city, :zip, :state, :phone, :email, :plan_id, :startdate, :updated)
    end
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]

  # GET /contractors
  # GET /contractors.json
  def index
    @contractors = Contractor.all
  end

  # GET /contractors/1
  # GET /contractors/1.json
  def show
  end

  # GET /contractors/new
  def new
    @contractor = Contractor.new
  end

  # GET /contractors/1/edit
  def edit
  end

  # POST /contractors
  # POST /contractors.json
  def create
    @contractor = Contractor.new(contractor_params)

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: 'Contractor was successfully created.' }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contractors/1
  # PATCH/PUT /contractors/1.json
  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: 'Contractor was successfully updated.' }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractors/1
  # DELETE /contractors/1.json
  def destroy
    @contractor.destroy
    respond_to do |format|
      format.html { redirect_to contractors_url, notice: 'Contractor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contractor_params
      params.require(:contractor).permit(:cont_id, :firstname, :lastname, :address1, :address2, :city, :zip, :state, :phone, :email, :startdate, :updated)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br>
    <%= f.number_field :plan_id %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :updated %><br>
    <%= f.datetime_select :updated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<div class="page-header">
  <h1>All Clients</h1>
</div>

<%= link_to 'New Client', new_client_path, class: "btn btn-success"%>
<div class="spacer">&nbsp;</div>
<% @clients.each do |client| %>
    <div class="client">
      <strong><%= client.firstname %></strong>
      <strong><%= client.lastname %></strong>
      <p class="address"><%= client.address1 %>
        <%= client.address2 %><br>
        <%= client.city %>
        <%= client.state %>
        <%= client.zip %></p>

      <p class="contact"><%= client.phone %><br>
                         <%= client.email %></p>

      <div class="meta">
      <%= link_to 'Joined ' + time_ago_in_words(client.startdate) + ' ago', client %>
      <span class="admin">
        | <%= link_to 'Edit', edit_client_path(client) %> |
        <%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
    </div>
<% end %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @client.client_id %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @client.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @client.lastname %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @client.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @client.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @client.plan_id %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @client.startdate %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @client.updated %>
</p>
<br>
<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/contractors/_form.html.erb
<%= form_for(@contractor) do |f| %>
  <% if @contractor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
      <% @contractor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cont_id %><br>
    <%= f.number_field :cont_id %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :updated %><br>
    <%= f.datetime_select :updated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contractors/edit.html.erb
<h1>Editing Contractor</h1>

<%= render 'form' %>

<%= link_to 'Show', @contractor %> |
<%= link_to 'Back', contractors_path %>

app/views/contractors/index.html.erb
<div class="page-header">
    <h1>All Contractors</h1>
</div>

<%= link_to 'New Contractor', new_contractor_path, class: "btn btn-success"%>
<div class="spacer">&nbsp;</div>
<% @contractors.each do |contractor| %>
   <div class="contractor">
        <strong><%= contractor.firstname %></strong>
        <strong><%= contractor.lastname %></strong>
        <p class="address"><%= contractor.address1 %>
                           <%= contractor.address2 %><br>
                           <%= contractor.city %>
                           <%= contractor.state %>
                           <%= contractor.zip %></p>
        <p class="contact"><%= contractor.phone %><br>
                           <%= mail_to contractor.email, 'Email me' %></p>
        <div class="meta">
            <%= link_to 'Joined ' + time_ago_in_words(contractor.startdate) + ' ago', contractor %>
            <span class="admin">
                | <%= link_to 'Edit', edit_contractor_path(contractor) %> |
                <%= link_to 'Destroy', contractor, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
        </div>
   </div>
<% end %>

<br>

app/views/contractors/new.html.erb
<h1>New Contractor</h1>

<%= render 'form' %>

<%= link_to 'Back', contractors_path %>

app/views/contractors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cont:</strong>
  <%= @contractor.cont_id %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @contractor.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @contractor.lastname %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @contractor.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @contractor.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @contractor.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @contractor.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @contractor.state %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contractor.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contractor.email %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @contractor.startdate %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @contractor.updated %>
</p>

<%= link_to 'Edit', edit_contractor_path(@contractor) %> |
<%= link_to 'Back', contractors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeHearthApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a href="/"><img src="/homehearth_trans.png" alt="H&H" width="40%"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clients<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Setup client care plan</a></li>
            <li><a href="/clients">List, Create & Edit clients</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Invoice client</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Print Client welcome package</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contractors<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/contractors">List, Create & Edit contractors</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Fill out contractor timesheet</a></li>
            <li><a href="#">Pay a contractor</a></li>
            <li><a href="#">Print paystub</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Print contractor welcome package</a></li>
            <li><a href="#">Print 1099 tax info</a></li>
          </ul>
        </li>

        <li><a href="#">Financials</a></li>

        <li><a href="#">HR documents</a></li>

      </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="what to search for">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<br>
<br>
<br>

<h2 class="welcome">Welcome to another day At The Office</h2>
<p class="welcome">
  <br>
  The above menu system should take you anywhere you need to go today.
</p>